---
# defaults file for httpd

ocp_version: "{{ lookup('env', 'OCP_VERSION') | default('4.10', true) }}"

ocp_clients:
  - "openshift-client-linux.tar.gz"
  - "openshift-install-linux.tar.gz"
  - "oc-mirror.tar.gz"
  - "opm-linux.tar.gz"
  - "ccoctl-linux.tar.gz"

ocp_deps:
  - "rhcos-live.x86_64.iso"
