---
# defaults file for httpd

ocp_version: "{{ lookup('env', 'OCP_VERSION') | default('4.10', true) }}"

ocp_clients:
  - { name: "openshift-install-linux.tar.gz", value: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-{{ ocp_version }}" }
  - { name: "openshift-client-linux.tar.gz", value: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable" }
  - { name: "oc-mirror.tar.gz", value: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable" }
  - { name: "opm-linux.tar.gz", value: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable" }
  - { name: "ccoctl-linux.tar.gz", value: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable" }

ocp_deps:
  - "rhcos-live.x86_64.iso"

ibm_pak: "{{ lookup('env', 'IBM_PAK') | default('https://github.com/IBM/ibm-pak/releases/latest/download/oc-ibm_pak-linux-amd64.tar.gz', true) }}"
