---
# defaults file for httpd

ocp_version: "{{ lookup('env', 'OCP_VERSION') | default('4.10', true) }}"

ocp_client_version: "{{ lookup('env', 'OCP_CLIENT_VERSION') | default('4.12', true) }}"

ocp_clients:
  - "{{ ocp_client_version }}/openshift-client-linux.tar.gz"
  - "{{ ocp_version }}/openshift-install-linux.tar.gz"
  - "{{ ocp_client_version }}/oc-mirror.tar.gz"
  - "{{ ocp_client_version }}/opm-linux.tar.gz"
  - "{{ ocp_client_version }}/ccoctl-linux.tar.gz"

ocp_deps:
  - "rhcos-live.x86_64.iso"

ibm_pak: "{{ lookup('env', 'IBM_PAK') | default('https://github.com/IBM/ibm-pak/releases/latest/download/oc-ibm_pak-linux-amd64.tar.gz', true) }}"
