galaxy_info:
  author: Eric Kleinsorgen (@emk)
  description: Role to install httpd.

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibmce
    - ansible
    - ocp
    - day1

dependencies: []

