---
# defaults file for httpd
oai_disconnected: "{{ lookup('env', 'OAI_DISCONNECTED') | default('false', true) }}"
oai_registry_certificate: "{{ lookup('env', 'OAI_REGISTRY_CERTIFICATE') | default('/opt/mirror-registry/quay/quay-rootCA/rootCA.pem', true) }}"
oai_path: "{{ lookup('env', 'OAI_PATH') | default('/opt/oai', true) }}"
oai_certificate: "{{ lookup('env', 'OAI_CERTIFICATE') | default(oai_path + '/tls.crt', true) }}"
oai_key: "{{ lookup('env', 'OAI_KEY') | default(oai_path + '/tls.key', true) }}"
oai_ca_certificate: "{{ lookup('env', 'OAI_CA_CERTIFICATE') | default(oai_path + '/tls.crt', true) }}"
oai_pull_secret: "{{ lookup('env', 'OAI_PULL_SECRET') | default('/root/pull-secret', true) }}"