- name: Get the pull-secret file content
  shell: "cat {{ mirror_registry_secret }}"
  register: result

- name: Save the result data to a Variable as a Fact
  set_fact:
    pull_secret: "{{ result.stdout }}"

- name: Create pull-secret for mirror repository
  set_fact:
    registry_auth: "{{ lookup('template', 'registry_auth.json.j2') }}"

- name: "Mirror pull-secret json"
  debug:
    msg:
      - "pull-secret ............ {{ pull_secret }}"
      - "registry auth .......... {{ registry_auth }}"
      - "merged ................. {{ pull_secret | combine(registry_auth, recursive=true) }}"

- name: "Get OpenShift Version"
  shell: "openshift-install version | grep '^openshift-install' | awk '{print $2}'"
  register: openshift_version

- name: parse the OpenShift version data to variables as facts
  set_fact:
    ocp_major: "{{ openshift_version.stdout.split('.')[:2] | join('.') }}"
    ocp_minor: "{{ openshift_version.stdout }}"

- name: "OpenShift details"
  debug:
    msg:
      - "OpenShift Version ...... {{ ocp_major }}"
      - "OpenShift Major ........ {{ ocp_minor }}"

- name: "Template a file to {{ mirror_registry_path }}/imagesetconfig.yaml"
  ansible.builtin.template:
    src: imagesetconfig.yaml.j2
    dest: "{{ mirror_registry_path }}/imagesetconfig.yaml"

- name: "Create directory $XDG_RUNTIME_DIR/containers"
  file:
    path: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/containers/"
    state: directory

- name: "Copy merged pull secret to $XDG_RUNTIME_DIR/containers"
  copy:
    content: "{{ pull_secret | combine(registry_auth, recursive=true) }}"
    dest: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/containers/auth.json"

- name: "Copy pull secret to {{ mirror_registry_path }}/pull-secret"
  copy:
    content: "{{ registry_auth }}"
    dest: "{{ mirror_registry_path }}/pull-secret"

- name: "Mirror images :: oc mirror --skip-cleanup --dest-skip-tls --config imagesetconfig.yaml docker://{{ ansible_fqdn }}:8443/ibm"
  command: "oc mirror --skip-cleanup --dest-skip-tls --config imagesetconfig.yaml docker://{{ ansible_fqdn }}:8443/ibm"
  args:
    chdir: "{{ mirror_registry_path }}"

- name: "OpenShift Info"
  debug:
    msg:
      - "pull-secret .......................... {{ registry_auth }}"
      - "community-operator-index Catalog ..... {{ mirror_registry_path }}/oc-mirror-workspace/results-*/catalogSource-community-operator-index.yaml"
      - "redhat-operator-index Catalog ........ {{ mirror_registry_path }}/oc-mirror-workspace/results-*/catalogSource-redhat-operator-index.yaml"
      - "ImageContentSourcePolicy ............. {{ mirror_registry_path }}/oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml"
      - "registry-cas ConfigMap ............... oc create configmap registry-cas -n openshift-config --from-file={{ ansible_fqdn }}..8443={{ mirror_registry_path }}/quay/quay-rootCA/rootCA.pem"
      - "Patch image config ................... oc patch image.config.openshift.io/cluster --patch '{\"spec\":{\"additionalTrustedCA\":{\"name\":\"registry-cas\"}}}' --type=merge"
