- name: "Create directory for mirror-registry"
  file:
    path: "{{ mirror_registry_path }}/{{ item }}"
    state: directory
  loop:
    - 'auth'
    - 'certs'
    - 'lib'
    - 'etc/docker/registry'

- name: Create private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ mirror_registry_path }}/certs/registry.key"

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ mirror_registry_path }}/certs/registry.key"
    common_name: "{{ ansible_fqdn }}"
    organization_name: Compu-Global-Hyper-Mega-Net
    subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "IP:{{ ansible_default_ipv4.address }}"
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
  register: csr

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ mirror_registry_path }}/certs/registry.crt"
    csr_content: "{{ csr.csr }}"
    privatekey_path: "{{ mirror_registry_path }}/certs/registry.key"
    provider: selfsigned

- name: Create htpasswd file for registry
  command: "htpasswd -cBb {{ mirror_registry_path }}/auth/htpasswd {{ mirror_registry_user }} {{ mirror_registry_password }}"

- name: "Install mirror-registry"
  command: "podman run --detach --network=host --name registry --hostname day1 -v {{ mirror_registry_path }}/auth:/auth -v {{ mirror_registry_path }}/certs:/certs -v {{ mirror_registry_path }}/lib:/var/lib/registry:Z -e \"REGISTRY_AUTH=htpasswd\" -e \"REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm\" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd -e REGISTRY_HTTP_ADDR=0.0.0.0:8443 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt -e REGISTRY_HTTP_TLS_KEY=/certs/registry.key docker.io/library/registry:2.7.1"

- name: Add ports to firewall
  firewalld:
    port: "8443/tcp"
    state: enabled
    immediate: true
    permanent: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  register: ports_added_to_firewalld

- name: "Ports Added"
  debug:
    var: ports_added_to_firewalld

- name: "OpenShift Mirror registry details"
  debug:
    msg:
      - "Mirror-registry .............. https://{{ ansible_nodename }}:8443"
      - "User ......................... {{ mirror_registry_user }}"
      - "Password ..................... {{ mirror_registry_password }}"
      - "Certificate .................. {{ mirror_registry_path }}/certs/registry.crt }}"
