- name: "Get OpenShift COMMIT_ID"
  shell: "openshift-install version | grep '^built from commit' | awk '{print $4}'"
  register: commit_id

- name: "OpenShift Assisted Installer details"
  debug:
    msg:
      - "COMMIT_ID .............. {{ commit_id.stdout }}"

- name: "OpenShift Details"
  uri:
    url: https://raw.githubusercontent.com/openshift/installer/{{ commit_id.stdout }}/data/data/coreos/rhcos.json
    return_content: true
  register: rhcos

- name: "OpenShift RHCOS details"
  debug:
    msg:
      - "RELEASE ............... {{ rhcos.content.architectures.x86_64.artifacts.metal.release }}"
      - "Live ISO .............. {{ rhcos.content.architectures.x86_64.artifacts.metal.formats.iso.disk.location }}"

