- name: "Get OpenShift COMMIT_ID"
  shell: "openshift-install version | grep '^built from commit' | awk '{print $4}'"
  register: commit_id

- name: "OpenShift Assisted Installer details"
  debug:
    msg:
      - "COMMIT_ID .............. {{ commit_id.stdout }}"

- name: "rhcos.json"
  get_url:
    url: "https://raw.githubusercontent.com/openshift/installer/{{ commit_id.stdout }}/data/data/coreos/rhcos.json"
    dest: "/tmp/rhcos.json"
    mode: '0644'

- name: Display the JSON file content
  shell: cat /tmp/rhcos.json
  register: result

- name: save the Json data to a Variable as a Fact
  set_fact:
    jsondata: "{{ result.stdout | from_json }}"

#- name: "OpenShift Details"
#  uri:
#    url: https://raw.githubusercontent.com/openshift/installer/{{ commit_id.stdout }}/data/data/coreos/rhcos.json
#    return_content: true
#  register: rhcos

- name: "OpenShift RHCOS details"
  debug:
    msg:
      - "rhcos ................. {{ jsondata }}"
#      - "RELEASE ............... {{ rhcos.content.architectures.x86_64.artifacts.metal.release }}"
#      - "Live ISO .............. {{ rhcos.content.architectures.x86_64.artifacts.metal.formats.iso.disk.location }}"

