---
# defaults file for httpd

mirror_registry_package: "{{ lookup('env', 'MIRROR_REGISTRY_PACKAGE') | default('https://mirror.openshift.com/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz', true) }}"
mirror_registry_path: "{{ lookup('env', 'MIRROR_REGISTRY_PATH') | default('/opt/mirror-registry', true) }}"
